name: Build and publish to PyPi
on:
  push:
    tags: ["*"]

permissions: {}

jobs:
  pypi-publish:
    if: github.repository == 'mweinelt/kea-exporter'
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v6
      - name: Build package
        run: uv build
      - name: Publish package distributions to PyPI
        run: uv publish
