name: Build and publish to PyPi
on:
  push:
    tags: ["*"]

# https://pdm-project.org/latest/usage/publish/
jobs:
  pypi-publish:
    if: github.repository == 'mweinelt/kea-exporter'
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
      - name: Publish package distributions to PyPI
        run: pdm publish
